pipeline {
    agent any
    options {
        lock(quantity: 1, resource: 'container-build-lock', variable: 'CONTAINER_BUILD_LOCK')
        buildDiscarder(logRotator(numToKeepStr:'10'))
    }
    stages {
        stage('Build') {
            steps {
                script {
                    properties([
                        parameters([
                            string(
                                defaultValue: '',
                                name: 'BASE_VERSION',
                                trim: true
                            ),
                            string(
                                defaultValue: '',
                                name: 'VERSION',
                                trim: true
                            )
                        ])
                    ])
                    currentBuild.displayName = "languages ${params.VERSION}"
                    currentBuild.description = "languages container image build"
                    result = sh(label: 'build', returnStatus: true, script: "languages/build.sh ${params.BASE_VERSION} ${params.VERSION}")
                    if (result == 1) {
                        currentBuild.result = 'FAILURE'
                        echo '[FAILURE] build failed'
                        return
                    }
                }
            }
        }
    }
}