pipeline {
    agent any
    options {
        lock(quantity: 1, resource: 'container-build-lock', variable: 'CONTAINER_BUILD_LOCK')
        buildDiscarder(logRotator(numToKeepStr:'10'))
    }
    stages {
        stage('Build') {
            steps {
                script {
                    currentBuild.displayName = "base ${params.VERSION}"
                    currentBuild.description = "base container image build"
                    result = sh(label: 'build', returnStatus: true, script: "base/build.sh ${params.VERSION}")
                    if (result == 1) {
                        currentBuild.result = 'FAILURE'
                        echo '[FAILURE] build failed'
                        return
                    }
                }
            }
            post {
                success {
                    build job: 'languages', parameters: [
                        string(name: 'BASE_VERSION', value: "${params.VERSION}")
                    ]
                }
            }
        }
    }
}